filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
build:
  environment:
    php:
      version: 7.3.8
  dependencies:
    before:
      - composer require phpunit/phpunit:^7.0 --dev
  tests:
    override:
      -
        command: vendor/bin/phpunit tests/unit --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
